GET http://localhost:5102/games

###
GET http://localhost:5102/games/1

###
POST http://localhost:5102/games
Content-Type: application/json

{
    "name": "Grand Theft Auto 6",
    "genreId": 1,
    "price": 99.99,
    "releaseDate": "2026-11-19"
}

###
POST http://localhost:5102/games
Content-Type: application/json

{
    "name": "The Blue Nowhere",
    "genreId": 1,
    "price": 14.99,
    "releaseDate": "2027-03-05"
}

###
PUT http://localhost:5102/games/2
Content-Type: application/json

{
    "name": "Mi.mi.co",
    "genreId": 1,
    "price": 24.99,
    "releaseDate": "2026-12-24"
}

###
DELETE http://localhost:5102/games/3

###
GET http://localhost:5102/genres